/* Generated by Yosys 0.29+11 (git sha1 acfdc5cc4, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module REGISTER_16BIT(clk, rst, en, din, dout);
  wire [15:0] _0_;
  reg [15:0] _1_;
  input clk;
  wire clk;
  input [15:0] din;
  wire [15:0] din;
  output [15:0] dout;
  wire [15:0] dout;
  input en;
  wire en;
  wire [15:0] \reg ;
  input rst;
  wire rst;
  always @(posedge clk, posedge rst)
    if (rst) _1_ <= 16'h0000;
    else _1_ <= _0_;
  assign _0_ = en ? din : \reg ;
  assign \reg  = _1_;
  assign dout = \reg ;
endmodule
